//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - AddResultRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "AddResultRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class AddResultRequest
	{
		private int studentID;
	 	private int qualificationID;
	 	private int year;
	 	private short keyStageID;
	 	private int pointID;
	 	private char seasonCode;
	 		
		[WCF::MessageBodyMember(Name = "StudentID")] 
		public int StudentID
		{
			get { return studentID; }
			set { studentID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "QualificationID")] 
		public int QualificationID
		{
			get { return qualificationID; }
			set { qualificationID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Year")] 
		public int Year
		{
			get { return year; }
			set { year = value; }
		}
			
		[WCF::MessageBodyMember(Name = "KeyStageID")] 
		public short KeyStageID
		{
			get { return keyStageID; }
			set { keyStageID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "PointID")] 
		public int PointID
		{
			get { return pointID; }
			set { pointID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "SeasonCode")] 
		public char SeasonCode
		{
			get { return seasonCode; }
			set { seasonCode = value; }
		}
	}
}

