//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - AddToUserPasswordLetterRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "AddToUserPasswordLetterRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class AddToUserPasswordLetterRequest
	{
		private string username;
	 	private bool checkQueueStatus;
	 	private Web09.Services.DataContracts.UserContext userContext;
	 	private string consumerURL;
	 		
		[WCF::MessageBodyMember(Name = "Username")] 
		public string Username
		{
			get { return username; }
			set { username = value; }
		}
			
		[WCF::MessageBodyMember(Name = "CheckQueueStatus")] 
		public bool CheckQueueStatus
		{
			get { return checkQueueStatus; }
			set { checkQueueStatus = value; }
		}
			
		[WCF::MessageBodyMember(Name = "UserContext")] 
		public Web09.Services.DataContracts.UserContext UserContext
		{
			get { return userContext; }
			set { userContext = value; }
		}
			
		[WCF::MessageBodyMember(Name = "ConsumerURL")] 
		public string ConsumerURL
		{
			get { return consumerURL; }
			set { consumerURL = value; }
		}
	}
}

