//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - AttachPupilAdjustmentEvidenceRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "AttachPupilAdjustmentEvidenceRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class AttachPupilAdjustmentEvidenceRequest
	{
		private Web09.Services.DataContracts.CompletedPupilAdjustment completedPupilAdjustment;
	 	private Web09.Services.DataContracts.UserContext userContext;
	 	private string barcode;
	 	private string documentPath;
	 	private string documentType;
	 		
		[WCF::MessageBodyMember(Name = "CompletedPupilAdjustment")] 
		public Web09.Services.DataContracts.CompletedPupilAdjustment CompletedPupilAdjustment
		{
			get { return completedPupilAdjustment; }
			set { completedPupilAdjustment = value; }
		}
			
		[WCF::MessageBodyMember(Name = "UserContext")] 
		public Web09.Services.DataContracts.UserContext UserContext
		{
			get { return userContext; }
			set { userContext = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Barcode")] 
		public string Barcode
		{
			get { return barcode; }
			set { barcode = value; }
		}
			
		[WCF::MessageBodyMember(Name = "DocumentPath")] 
		public string DocumentPath
		{
			get { return documentPath; }
			set { documentPath = value; }
		}
			
		[WCF::MessageBodyMember(Name = "DocumentType")] 
		public string DocumentType
		{
			get { return documentType; }
			set { documentType = value; }
		}
	}
}

