//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - AttachEvidenceRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "AttachEvidenceRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class AttachEvidenceRequest
	{
		private int resultID;
	 	private int changeID;
	 	private string barcode;
	 	private string documentPath;
	 	private string documentType;
	 		
		[WCF::MessageBodyMember(Name = "ResultID")] 
		public int ResultID
		{
			get { return resultID; }
			set { resultID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "ChangeID")] 
		public int ChangeID
		{
			get { return changeID; }
			set { changeID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Barcode")] 
		public string Barcode
		{
			get { return barcode; }
			set { barcode = value; }
		}
			
		[WCF::MessageBodyMember(Name = "DocumentPath")] 
		public string DocumentPath
		{
			get { return documentPath; }
			set { documentPath = value; }
		}
			
		[WCF::MessageBodyMember(Name = "DocumentType")] 
		public string DocumentType
		{
			get { return documentType; }
			set { documentType = value; }
		}
	}
}

