//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - DoLateResultsExistResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class DoLateResultsExistResponse
	{
		private int resultsExist;
	 		
		[WCF::MessageBodyMember(Name = "ResultsExist")] 
		public int ResultsExist
		{
			get { return resultsExist; }
			set { resultsExist = value; }
		}
	}
}

