//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetAllPilotSchoolsResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetAllPilotSchoolsResponse
	{
		private Web09.Services.DataContracts.Schools pilotSchoolList;
	 		
		[WCF::MessageBodyMember(Name = "PilotSchoolList")] 
		public Web09.Services.DataContracts.Schools PilotSchoolList
		{
			get { return pilotSchoolList; }
			set { pilotSchoolList = value; }
		}
	}
}

