//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetCohortDecisionPageResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetCohortDecisionPageResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetCohortDecisionPageResponse
	{
		private Web09.Services.DataContracts.CohortDecisionResults cohortDecisionList;
	 	private int totalRowCount;
	 		
		[WCF::MessageBodyMember(Name = "CohortDecisionList")] 
		public Web09.Services.DataContracts.CohortDecisionResults CohortDecisionList
		{
			get { return cohortDecisionList; }
			set { cohortDecisionList = value; }
		}
			
		[WCF::MessageBodyMember(Name = "TotalRowCount")] 
		public int TotalRowCount
		{
			get { return totalRowCount; }
			set { totalRowCount = value; }
		}
	}
}

