//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetCohortDetailsCountResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetCohortDetailsCountResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class GetCohortDetailsCountResponse
	{
		private int cohortDetailsCount;
	 		
		[WCF::MessageBodyMember(Name = "CohortDetailsCount")] 
		public int CohortDetailsCount
		{
			get { return cohortDetailsCount; }
			set { cohortDetailsCount = value; }
		}
	}
}

