//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetCohortDetailsResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetCohortDetailsResponse
	{
		private Web09.Services.DataContracts.CohortPupilList cohortDetails;
	 		
		[WCF::MessageBodyMember(Name = "CohortDetails")] 
		public Web09.Services.DataContracts.CohortPupilList CohortDetails
		{
			get { return cohortDetails; }
			set { cohortDetails = value; }
		}
	}
}

