//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetContentRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetContentRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetContentRequest
	{
		private string contentURI;
	 	private string context;
	 		
		[WCF::MessageBodyMember(Name = "ContentURI")] 
		public string ContentURI
		{
			get { return contentURI; }
			set { contentURI = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Context")] 
		public string Context
		{
			get { return context; }
			set { context = value; }
		}
	}
}

