//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetCallTypesResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetCallTypesResponse
	{
		private Web09.Services.DataContracts.CallTypes callTypes;
	 		
		[WCF::MessageBodyMember(Name = "CallTypes")] 
		public Web09.Services.DataContracts.CallTypes CallTypes
		{
			get { return callTypes; }
			set { callTypes = value; }
		}
	}
}

