//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetCohortAdjustmentRequestSummaryRequest
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetCohortAdjustmentRequestSummaryRequest
	{
		private short keystage;
	 		
		[WCF::MessageBodyMember(Name = "Keystage")] 
		public short Keystage
		{
			get { return keystage; }
			set { keystage = value; }
		}
	}
}

