//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetFAQListRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetFAQListRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class GetFAQListRequest
	{
		private System.Nullable<short> cohortID;
	 	private System.Nullable<short> schoolGroupID;
	 	private System.Nullable<short> faqCategoryID;
	 	private System.Nullable<bool> june;
	 	private System.Nullable<bool> sept;
	 	private System.Nullable<bool> active;
	 		
		[WCF::MessageBodyMember(Name = "CohortID")] 
		public System.Nullable<short> CohortID
		{
			get { return cohortID; }
			set { cohortID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "SchoolGroupID")] 
		public System.Nullable<short> SchoolGroupID
		{
			get { return schoolGroupID; }
			set { schoolGroupID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "FaqCategoryID")] 
		public System.Nullable<short> FaqCategoryID
		{
			get { return faqCategoryID; }
			set { faqCategoryID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "June")] 
		public System.Nullable<bool> June
		{
			get { return june; }
			set { june = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Sept")] 
		public System.Nullable<bool> Sept
		{
			get { return sept; }
			set { sept = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Active")] 
		public System.Nullable<bool> Active
		{
			get { return active; }
			set { active = value; }
		}
	}
}

