//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetFAQByIDRequest
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetFAQByIDRequest
	{
		private short fAQID;
	 		
		[WCF::MessageBodyMember(Name = "FAQID")] 
		public short FAQID
		{
			get { return fAQID; }
			set { fAQID = value; }
		}
	}
}

