//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetGradesForResultsRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetGradesForResultsRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class GetGradesForResultsRequest
	{
		private int qANID;
	 	private int qualificationTypeID;
	 	private short studentKeystage;
	 		
		[WCF::MessageBodyMember(Name = "QANID")] 
		public int QANID
		{
			get { return qANID; }
			set { qANID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "QualificationTypeID")] 
		public int QualificationTypeID
		{
			get { return qualificationTypeID; }
			set { qualificationTypeID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "StudentKeystage")] 
		public short StudentKeystage
		{
			get { return studentKeystage; }
			set { studentKeystage = value; }
		}
	}
}

