//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetHelpListForPageV2Request
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetHelpListForPageV2Request", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class GetHelpListForPageV2Request
	{
		private string pageName;
	 	private string userLevel;
	 	private string keyStageList;
	 	private string schoolGroupIDList;
	 		
		[WCF::MessageBodyMember(Name = "PageName")] 
		public string PageName
		{
			get { return pageName; }
			set { pageName = value; }
		}
			
		[WCF::MessageBodyMember(Name = "UserLevel")] 
		public string UserLevel
		{
			get { return userLevel; }
			set { userLevel = value; }
		}
			
		[WCF::MessageBodyMember(Name = "KeyStageList")] 
		public string KeyStageList
		{
			get { return keyStageList; }
			set { keyStageList = value; }
		}
			
		[WCF::MessageBodyMember(Name = "SchoolGroupIDList")] 
		public string SchoolGroupIDList
		{
			get { return schoolGroupIDList; }
			set { schoolGroupIDList = value; }
		}
	}
}

