//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetKeyStageConfigurationResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetKeyStageConfigurationResponse
	{
		private Web09.Services.DataContracts.KeyStageConfigurationList keyStageConfigurationList;
	 		
		[WCF::MessageBodyMember(Name = "KeyStageConfigurationList")] 
		public Web09.Services.DataContracts.KeyStageConfigurationList KeyStageConfigurationList
		{
			get { return keyStageConfigurationList; }
			set { keyStageConfigurationList = value; }
		}
	}
}

