//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetLateResultsV2Request
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetLateResultsV2Request", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class GetLateResultsV2Request
	{
		private int dCSFNumber;
	 	private int keyStage;
	 	private int page;
	 	private int rowsPerPage;
	 	private string sortOrder;
	 	private int sortAscending;
	 		
		[WCF::MessageBodyMember(Name = "DCSFNumber")] 
		public int DCSFNumber
		{
			get { return dCSFNumber; }
			set { dCSFNumber = value; }
		}
			
		[WCF::MessageBodyMember(Name = "KeyStage")] 
		public int KeyStage
		{
			get { return keyStage; }
			set { keyStage = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Page")] 
		public int Page
		{
			get { return page; }
			set { page = value; }
		}
			
		[WCF::MessageBodyMember(Name = "RowsPerPage")] 
		public int RowsPerPage
		{
			get { return rowsPerPage; }
			set { rowsPerPage = value; }
		}
			
		[WCF::MessageBodyMember(Name = "SortOrder")] 
		public string SortOrder
		{
			get { return sortOrder; }
			set { sortOrder = value; }
		}
			
		[WCF::MessageBodyMember(Name = "SortAscending")] 
		public int SortAscending
		{
			get { return sortAscending; }
			set { sortAscending = value; }
		}
	}
}

