//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetLateResultsRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetLateResultsRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm/services")] 
	public partial class GetLateResultsRequest
	{
		private int page;
	 	private int rowsPerPage;
	 	private int dCSFNumber;
	 	private System.Nullable<short> keyStageId;
	 	private string sortExpression;
	 		
		[WCF::MessageBodyMember(Name = "Page")] 
		public int Page
		{
			get { return page; }
			set { page = value; }
		}
			
		[WCF::MessageBodyMember(Name = "RowsPerPage")] 
		public int RowsPerPage
		{
			get { return rowsPerPage; }
			set { rowsPerPage = value; }
		}
			
		[WCF::MessageBodyMember(Name = "DCSFNumber")] 
		public int DCSFNumber
		{
			get { return dCSFNumber; }
			set { dCSFNumber = value; }
		}
			
		[WCF::MessageBodyMember(Name = "KeyStageId")] 
		public System.Nullable<short> KeyStageId
		{
			get { return keyStageId; }
			set { keyStageId = value; }
		}
			
		[WCF::MessageBodyMember(Name = "SortExpression")] 
		public string SortExpression
		{
			get { return sortExpression; }
			set { sortExpression = value; }
		}
	}
}

