//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetMessageByIDRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetMessageByIDRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class GetMessageByIDRequest
	{
		private short messageID;
	 	private bool includeSchools;
	 		
		[WCF::MessageBodyMember(Name = "MessageID")] 
		public short MessageID
		{
			get { return messageID; }
			set { messageID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "IncludeSchools")] 
		public bool IncludeSchools
		{
			get { return includeSchools; }
			set { includeSchools = value; }
		}
	}
}

