//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetMessageSchoolsRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetMessageSchoolsRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class GetMessageSchoolsRequest
	{
		private short messageID;
	 	private int page;
	 	private int rowsPerPage;
	 		
		[WCF::MessageBodyMember(Name = "MessageID")] 
		public short MessageID
		{
			get { return messageID; }
			set { messageID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Page")] 
		public int Page
		{
			get { return page; }
			set { page = value; }
		}
			
		[WCF::MessageBodyMember(Name = "RowsPerPage")] 
		public int RowsPerPage
		{
			get { return rowsPerPage; }
			set { rowsPerPage = value; }
		}
	}
}

