//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetMessageListV2Request
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetMessageListV2Request", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class GetMessageListV2Request
	{
		private int dFESNumber;
	 	private int keyStage;
	 	private bool isActive;
	 		
		[WCF::MessageBodyMember(Name = "DFESNumber")] 
		public int DFESNumber
		{
			get { return dFESNumber; }
			set { dFESNumber = value; }
		}
			
		[WCF::MessageBodyMember(Name = "KeyStage")] 
		public int KeyStage
		{
			get { return keyStage; }
			set { keyStage = value; }
		}
			
		[WCF::MessageBodyMember(Name = "IsActive")] 
		public bool IsActive
		{
			get { return isActive; }
			set { isActive = value; }
		}
	}
}

