//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetPupilRequestInfoResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetPupilRequestInfoResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetPupilRequestInfoResponse
	{
		private Web09.Services.DataContracts.CompletedPupilAdjustment completedAdjustment;
	 	private Web09.Services.DataContracts.ValidationFailureList informationMessageList;
	 	private Web09.Services.DataContracts.ValidationFailureList warningMessageList;
	 	private Web09.Services.DataContracts.ValidationFailureList errorMessageList;
	 		
		[WCF::MessageBodyMember(Name = "CompletedAdjustment")] 
		public Web09.Services.DataContracts.CompletedPupilAdjustment CompletedAdjustment
		{
			get { return completedAdjustment; }
			set { completedAdjustment = value; }
		}
			
		[WCF::MessageBodyMember(Name = "InformationMessageList")] 
		public Web09.Services.DataContracts.ValidationFailureList InformationMessageList
		{
			get { return informationMessageList; }
			set { informationMessageList = value; }
		}
			
		[WCF::MessageBodyMember(Name = "WarningMessageList")] 
		public Web09.Services.DataContracts.ValidationFailureList WarningMessageList
		{
			get { return warningMessageList; }
			set { warningMessageList = value; }
		}
			
		[WCF::MessageBodyMember(Name = "ErrorMessageList")] 
		public Web09.Services.DataContracts.ValidationFailureList ErrorMessageList
		{
			get { return errorMessageList; }
			set { errorMessageList = value; }
		}
	}
}

