//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetPasswordLetterDataResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetPasswordLetterDataResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetPasswordLetterDataResponse
	{
		private Web09.Services.DataContracts.PasswordLetterDataList requiredLetters;
	 		
		[WCF::MessageBodyMember(Name = "RequiredLetters")] 
		public Web09.Services.DataContracts.PasswordLetterDataList RequiredLetters
		{
			get { return requiredLetters; }
			set { requiredLetters = value; }
		}
	}
}

