//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetPupilRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetPupilRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetPupilRequest
	{
		private int pupilID;
	 	private Web09.Services.DataContracts.StudentChangeStatus studentChangeStatus;
	 		
		[WCF::MessageBodyMember(Name = "PupilID")] 
		public int PupilID
		{
			get { return pupilID; }
			set { pupilID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "StudentChangeStatus")] 
		public Web09.Services.DataContracts.StudentChangeStatus StudentChangeStatus
		{
			get { return studentChangeStatus; }
			set { studentChangeStatus = value; }
		}
	}
}

