//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetPupilFilterListsV2Response
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetPupilFilterListsV2Response", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetPupilFilterListsV2Response
	{
		private string jSON;
	 		
		[WCF::MessageBodyMember(Name = "JSON")] 
		public string JSON
		{
			get { return jSON; }
			set { jSON = value; }
		}
	}
}

