//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetPupilAdjustmentReasonsRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetPupilAdjustmentReasonsRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetPupilAdjustmentReasonsRequest
	{
		private int pupilID;
	 	private Web09.Services.DataContracts.PromptAnswer initialQuestionAnswer;
	 	private Web09.Services.DataContracts.UserContext userContext;
	 	private Web09.Services.DataContracts.PupilAdjustmentType pupilAdjustmentType;
	 		
		[WCF::MessageBodyMember(Name = "PupilID")] 
		public int PupilID
		{
			get { return pupilID; }
			set { pupilID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "InitialQuestionAnswer")] 
		public Web09.Services.DataContracts.PromptAnswer InitialQuestionAnswer
		{
			get { return initialQuestionAnswer; }
			set { initialQuestionAnswer = value; }
		}
			
		[WCF::MessageBodyMember(Name = "UserContext")] 
		public Web09.Services.DataContracts.UserContext UserContext
		{
			get { return userContext; }
			set { userContext = value; }
		}
			
		[WCF::MessageBodyMember(Name = "PupilAdjustmentType")] 
		public Web09.Services.DataContracts.PupilAdjustmentType PupilAdjustmentType
		{
			get { return pupilAdjustmentType; }
			set { pupilAdjustmentType = value; }
		}
	}
}

