//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetPupilRequestInfoRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetPupilRequestInfoRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetPupilRequestInfoRequest
	{
		private int studentRequestID;
	 		
		[WCF::MessageBodyMember(Name = "StudentRequestID")] 
		public int StudentRequestID
		{
			get { return studentRequestID; }
			set { studentRequestID = value; }
		}
	}
}

