//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetPupilsWithoutResultRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetPupilsWithoutResultRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetPupilsWithoutResultRequest
	{
		private int dCSFNumber;
	 	private short keyStage;
	 		
		[WCF::MessageBodyMember(Name = "DCSFNumber")] 
		public int DCSFNumber
		{
			get { return dCSFNumber; }
			set { dCSFNumber = value; }
		}
			
		[WCF::MessageBodyMember(Name = "KeyStage")] 
		public short KeyStage
		{
			get { return keyStage; }
			set { keyStage = value; }
		}
	}
}

