//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetPupilAttainmentValuesResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetPupilAttainmentValuesResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetPupilAttainmentValuesResponse
	{
		private Web09.Services.DataContracts.PupilAttainmentItemCollection valuesList;
	 		
		[WCF::MessageBodyMember(Name = "ValuesList")] 
		public Web09.Services.DataContracts.PupilAttainmentItemCollection ValuesList
		{
			get { return valuesList; }
			set { valuesList = value; }
		}
	}
}

