//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetPasswordLettersToSendResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetPasswordLettersToSendResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetPasswordLettersToSendResponse
	{
		private System.Collections.Generic.List<string> users;
	 		
		[WCF::MessageBodyMember(Name = "Users")] 
		public System.Collections.Generic.List<string> Users
		{
			get { return users; }
			set { users = value; }
		}
	}
}

