//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetPupilWithResultsCountResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetPupilWithResultsCountResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetPupilWithResultsCountResponse
	{
		private int pupilWithResultsCount;
	 		
		[WCF::MessageBodyMember(Name = "PupilWithResultsCount")] 
		public int PupilWithResultsCount
		{
			get { return pupilWithResultsCount; }
			set { pupilWithResultsCount = value; }
		}
	}
}

