//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetQualificationsBySchoolRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetQualificationsBySchoolRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class GetQualificationsBySchoolRequest
	{
		private int dFESNumber;
	 	private short keystage;
	 		
		[WCF::MessageBodyMember(Name = "DFESNumber")] 
		public int DFESNumber
		{
			get { return dFESNumber; }
			set { dFESNumber = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Keystage")] 
		public short Keystage
		{
			get { return keystage; }
			set { keystage = value; }
		}
	}
}

