//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetResultAdjustmentRequestCountRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetResultAdjustmentRequestCountRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetResultAdjustmentRequestCountRequest
	{
		private Web09.Services.DataContracts.CohortAdjustmentRequestsFilter resultAdjustmentRequestFilter;
	 		
		[WCF::MessageBodyMember(Name = "ResultAdjustmentRequestFilter")] 
		public Web09.Services.DataContracts.CohortAdjustmentRequestsFilter ResultAdjustmentRequestFilter
		{
			get { return resultAdjustmentRequestFilter; }
			set { resultAdjustmentRequestFilter = value; }
		}
	}
}

