//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetResultAdjustmentRequestPageResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetResultAdjustmentRequestPageResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetResultAdjustmentRequestPageResponse
	{
		private Web09.Services.DataContracts.CohortAdjustmentRequestResults resultAdjustmentRequestList;
	 	private int totalRowCount;
	 		
		[WCF::MessageBodyMember(Name = "ResultAdjustmentRequestList")] 
		public Web09.Services.DataContracts.CohortAdjustmentRequestResults ResultAdjustmentRequestList
		{
			get { return resultAdjustmentRequestList; }
			set { resultAdjustmentRequestList = value; }
		}
			
		[WCF::MessageBodyMember(Name = "TotalRowCount")] 
		public int TotalRowCount
		{
			get { return totalRowCount; }
			set { totalRowCount = value; }
		}
	}
}

