//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetResultAdjustmentRequestCountResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetResultAdjustmentRequestCountResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetResultAdjustmentRequestCountResponse
	{
		private int count;
	 		
		[WCF::MessageBodyMember(Name = "Count")] 
		public int Count
		{
			get { return count; }
			set { count = value; }
		}
	}
}

