//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetResultsForStudentsRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetResultsForStudentsRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class GetResultsForStudentsRequest
	{
		private System.Collections.Generic.List<int> pupilList;
	 	private string resultType;
	 	private string qualification;
	 	private string qAN;
	 	private string awardingBody;
	 	private string syllabus;
	 	private int year;
	 	private string session;
	 	private string subjectTitle;
	 	private short studentKeystage;
	 		
		[WCF::MessageBodyMember(Name = "PupilList")] 
		public System.Collections.Generic.List<int> PupilList
		{
			get { return pupilList; }
			set { pupilList = value; }
		}
			
		[WCF::MessageBodyMember(Name = "ResultType")] 
		public string ResultType
		{
			get { return resultType; }
			set { resultType = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Qualification")] 
		public string Qualification
		{
			get { return qualification; }
			set { qualification = value; }
		}
			
		[WCF::MessageBodyMember(Name = "QAN")] 
		public string QAN
		{
			get { return qAN; }
			set { qAN = value; }
		}
			
		[WCF::MessageBodyMember(Name = "AwardingBody")] 
		public string AwardingBody
		{
			get { return awardingBody; }
			set { awardingBody = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Syllabus")] 
		public string Syllabus
		{
			get { return syllabus; }
			set { syllabus = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Year")] 
		public int Year
		{
			get { return year; }
			set { year = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Session")] 
		public string Session
		{
			get { return session; }
			set { session = value; }
		}
			
		[WCF::MessageBodyMember(Name = "SubjectTitle")] 
		public string SubjectTitle
		{
			get { return subjectTitle; }
			set { subjectTitle = value; }
		}
			
		[WCF::MessageBodyMember(Name = "StudentKeystage")] 
		public short StudentKeystage
		{
			get { return studentKeystage; }
			set { studentKeystage = value; }
		}
	}
}

