//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetSchoolCheckingStatusResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetSchoolCheckingStatusResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetSchoolCheckingStatusResponse
	{
		private string currentCheckingStatus;
	 	private string lastUpdatedBy;
	 	private string lastUpdatedOn;
	 		
		[WCF::MessageBodyMember(Name = "CurrentCheckingStatus")] 
		public string CurrentCheckingStatus
		{
			get { return currentCheckingStatus; }
			set { currentCheckingStatus = value; }
		}
			
		[WCF::MessageBodyMember(Name = "LastUpdatedBy")] 
		public string LastUpdatedBy
		{
			get { return lastUpdatedBy; }
			set { lastUpdatedBy = value; }
		}
			
		[WCF::MessageBodyMember(Name = "LastUpdatedOn")] 
		public string LastUpdatedOn
		{
			get { return lastUpdatedOn; }
			set { lastUpdatedOn = value; }
		}
	}
}

