//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetSchoolRequest
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetSchoolRequest
	{
		private int schoolDFESNumber;
	 		
		[WCF::MessageBodyMember(Name = "SchoolDFESNumber")] 
		public int SchoolDFESNumber
		{
			get { return schoolDFESNumber; }
			set { schoolDFESNumber = value; }
		}
	}
}

