//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetSchoolValuesRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetSchoolValuesRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetSchoolValuesRequest
	{
		private int dFESNumber;
	 	private short keystage;
	 	private string valueType;
	 	private bool latest;
	 		
		[WCF::MessageBodyMember(Name = "DFESNumber")] 
		public int DFESNumber
		{
			get { return dFESNumber; }
			set { dFESNumber = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Keystage")] 
		public short Keystage
		{
			get { return keystage; }
			set { keystage = value; }
		}
			
		[WCF::MessageBodyMember(Name = "ValueType")] 
		public string ValueType
		{
			get { return valueType; }
			set { valueType = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Latest")] 
		public bool Latest
		{
			get { return latest; }
			set { latest = value; }
		}
	}
}

