//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetSchoolValuesByGroupResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetSchoolValuesByGroupResponse
	{
		private Web09.Services.DataContracts.SchoolValueItemCollection schoolValuesByGroup;
	 		
		[WCF::MessageBodyMember(Name = "SchoolValuesByGroup")] 
		public Web09.Services.DataContracts.SchoolValueItemCollection SchoolValuesByGroup
		{
			get { return schoolValuesByGroup; }
			set { schoolValuesByGroup = value; }
		}
	}
}

