//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetSchoolValuesSummaryV2Request
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetSchoolValuesSummaryV2Request", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetSchoolValuesSummaryV2Request
	{
		private string dFESNumber;
	 	private string keyStage;
	 	private string context;
	 		
		[WCF::MessageBodyMember(Name = "DFESNumber")] 
		public string DFESNumber
		{
			get { return dFESNumber; }
			set { dFESNumber = value; }
		}
			
		[WCF::MessageBodyMember(Name = "KeyStage")] 
		public string KeyStage
		{
			get { return keyStage; }
			set { keyStage = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Context")] 
		public string Context
		{
			get { return context; }
			set { context = value; }
		}
	}
}

