//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetScrutinyRejectionReasonsRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetScrutinyRejectionReasonsRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetScrutinyRejectionReasonsRequest
	{
		private short keystage;
	 	private bool isPLASC;
	 	private string requestType;
	 		
		[WCF::MessageBodyMember(Name = "Keystage")] 
		public short Keystage
		{
			get { return keystage; }
			set { keystage = value; }
		}
			
		[WCF::MessageBodyMember(Name = "IsPLASC")] 
		public bool IsPLASC
		{
			get { return isPLASC; }
			set { isPLASC = value; }
		}
			
		[WCF::MessageBodyMember(Name = "RequestType")] 
		public string RequestType
		{
			get { return requestType; }
			set { requestType = value; }
		}
	}
}

