//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetSchoolNORAdjustmentResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetSchoolNORAdjustmentResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetSchoolNORAdjustmentResponse
	{
		private Web09.Services.DataContracts.SchoolNORAdjustment requestInformation;
	 	private Web09.Services.DataContracts.CommonList requestedUpdateValues;
	 	private Web09.Services.DataContracts.CommonList requestedOriginalValues;
	 		
		[WCF::MessageBodyMember(Name = "RequestInformation")] 
		public Web09.Services.DataContracts.SchoolNORAdjustment RequestInformation
		{
			get { return requestInformation; }
			set { requestInformation = value; }
		}
			
		[WCF::MessageBodyMember(Name = "RequestedUpdateValues")] 
		public Web09.Services.DataContracts.CommonList RequestedUpdateValues
		{
			get { return requestedUpdateValues; }
			set { requestedUpdateValues = value; }
		}
			
		[WCF::MessageBodyMember(Name = "RequestedOriginalValues")] 
		public Web09.Services.DataContracts.CommonList RequestedOriginalValues
		{
			get { return requestedOriginalValues; }
			set { requestedOriginalValues = value; }
		}
	}
}

