//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetSchoolResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetSchoolResponse
	{
		private Web09.Services.DataContracts.School school;
	 		
		[WCF::MessageBodyMember(Name = "School")] 
		public Web09.Services.DataContracts.School School
		{
			get { return school; }
			set { school = value; }
		}
	}
}

