//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - LoginAuditRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "LoginAuditRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class LoginAuditRequest
	{
		private int dFESNumber;
	 	private string clientIPAddress;
	 	private string forename;
	 	private string surname;
	 	private string userID;
	 	private string userName;
	 	private string roleName;
	 		
		[WCF::MessageBodyMember(Name = "DFESNumber")] 
		public int DFESNumber
		{
			get { return dFESNumber; }
			set { dFESNumber = value; }
		}
			
		[WCF::MessageBodyMember(Name = "ClientIPAddress")] 
		public string ClientIPAddress
		{
			get { return clientIPAddress; }
			set { clientIPAddress = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Forename")] 
		public string Forename
		{
			get { return forename; }
			set { forename = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Surname")] 
		public string Surname
		{
			get { return surname; }
			set { surname = value; }
		}
			
		[WCF::MessageBodyMember(Name = "UserID")] 
		public string UserID
		{
			get { return userID; }
			set { userID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "UserName")] 
		public string UserName
		{
			get { return userName; }
			set { userName = value; }
		}
			
		[WCF::MessageBodyMember(Name = "RoleName")] 
		public string RoleName
		{
			get { return roleName; }
			set { roleName = value; }
		}
	}
}

