//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - MessageUnAssignAllRequest
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class MessageUnAssignAllRequest
	{
		private short messageIDField;
	 		
		[WCF::MessageBodyMember(Name = "messageID")] 
		public short messageID
		{
			get { return messageIDField; }
			set { messageIDField = value; }
		}
	}
}

