//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - MessageAssignAllRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "MessageAssignAllRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class MessageAssignAllRequest
	{
		private string dFESNumber;
	 	private Web09.Services.DataContracts.Cohorts cohorts;
	 	private Web09.Services.DataContracts.SchoolGroups schoolGroups;
	 	private short messageID;
	 	private System.Nullable<bool> submissionStatus;
	 		
		[WCF::MessageBodyMember(Name = "DFESNumber")] 
		public string DFESNumber
		{
			get { return dFESNumber; }
			set { dFESNumber = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Cohorts")] 
		public Web09.Services.DataContracts.Cohorts Cohorts
		{
			get { return cohorts; }
			set { cohorts = value; }
		}
			
		[WCF::MessageBodyMember(Name = "SchoolGroups")] 
		public Web09.Services.DataContracts.SchoolGroups SchoolGroups
		{
			get { return schoolGroups; }
			set { schoolGroups = value; }
		}
			
		[WCF::MessageBodyMember(Name = "MessageID")] 
		public short MessageID
		{
			get { return messageID; }
			set { messageID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "SubmissionStatus")] 
		public System.Nullable<bool> SubmissionStatus
		{
			get { return submissionStatus; }
			set { submissionStatus = value; }
		}
	}
}

