//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - Message1
	/// </summary>
	[WCF::MessageContract(WrapperName = "Message1", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class Message1
	{
		private int dCSFNumber;
	 	private short keyStageID;
	 		
		[WCF::MessageBodyMember(Name = "DCSFNumber")] 
		public int DCSFNumber
		{
			get { return dCSFNumber; }
			set { dCSFNumber = value; }
		}
			
		[WCF::MessageBodyMember(Name = "KeyStageID")] 
		public short KeyStageID
		{
			get { return keyStageID; }
			set { keyStageID = value; }
		}
	}
}

