//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ProcessInclusionPromptsResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "ProcessInclusionPromptsResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class ProcessInclusionPromptsResponse
	{
		private bool isAdjustmentComplete;
	 	private Web09.Services.DataContracts.PromptList promptList;
	 	private Web09.Services.DataContracts.CompletedPupilAdjustment completedAdjustment;
	 	private Web09.Services.DataContracts.CompletedPupilNonAdjustment completedNonAdjustment;
	 	private bool isAdjustmentCreated;
	 	private string newStudentID;
	 		
		[WCF::MessageBodyMember(Name = "IsAdjustmentComplete")] 
		public bool IsAdjustmentComplete
		{
			get { return isAdjustmentComplete; }
			set { isAdjustmentComplete = value; }
		}
			
		[WCF::MessageBodyMember(Name = "PromptList")] 
		public Web09.Services.DataContracts.PromptList PromptList
		{
			get { return promptList; }
			set { promptList = value; }
		}
			
		[WCF::MessageBodyMember(Name = "CompletedAdjustment")] 
		public Web09.Services.DataContracts.CompletedPupilAdjustment CompletedAdjustment
		{
			get { return completedAdjustment; }
			set { completedAdjustment = value; }
		}
			
		[WCF::MessageBodyMember(Name = "CompletedNonAdjustment")] 
		public Web09.Services.DataContracts.CompletedPupilNonAdjustment CompletedNonAdjustment
		{
			get { return completedNonAdjustment; }
			set { completedNonAdjustment = value; }
		}
			
		[WCF::MessageBodyMember(Name = "IsAdjustmentCreated")] 
		public bool IsAdjustmentCreated
		{
			get { return isAdjustmentCreated; }
			set { isAdjustmentCreated = value; }
		}
			
		[WCF::MessageBodyMember(Name = "NewStudentID")] 
		public string NewStudentID
		{
			get { return newStudentID; }
			set { newStudentID = value; }
		}
	}
}

