//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - RemovePupilRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "RemovePupilRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class RemovePupilRequest
	{
		private int studentID;
	 	private string adjustmentReasonID;
	 	private Web09.Services.DataContracts.Prompts prompts;
	 		
		[WCF::MessageBodyMember(Name = "StudentID")] 
		public int StudentID
		{
			get { return studentID; }
			set { studentID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "AdjustmentReasonID")] 
		public string AdjustmentReasonID
		{
			get { return adjustmentReasonID; }
			set { adjustmentReasonID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Prompts")] 
		public Web09.Services.DataContracts.Prompts Prompts
		{
			get { return prompts; }
			set { prompts = value; }
		}
	}
}

