//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - RequireSchoolStatusConfirmationResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "RequireSchoolStatusConfirmationResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class RequireSchoolStatusConfirmationResponse
	{
		private bool requireStatusConfirmation;
	 		
		[WCF::MessageBodyMember(Name = "RequireStatusConfirmation")] 
		public bool RequireStatusConfirmation
		{
			get { return requireStatusConfirmation; }
			set { requireStatusConfirmation = value; }
		}
	}
}

