//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - SaveCategoryRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "SaveCategoryRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class SaveCategoryRequest
	{
		private Web09.Services.DataContracts.FAQCategory category;
	 	private bool returnList;
	 		
		[WCF::MessageBodyMember(Name = "Category")] 
		public Web09.Services.DataContracts.FAQCategory Category
		{
			get { return category; }
			set { category = value; }
		}
			
		[WCF::MessageBodyMember(Name = "ReturnList")] 
		public bool ReturnList
		{
			get { return returnList; }
			set { returnList = value; }
		}
	}
}

