//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - SaveResultAdjustmentRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "SaveResultAdjustmentRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class SaveResultAdjustmentRequest
	{
		private Web09.Services.DataContracts.ResultAdjustmentChangeCollection requestIdChangeIdCollection;
	 	private string scrutinyStatusCode;
	 	private string comments;
	 	private System.Nullable<int> reasonId;
	 	private Web09.Services.DataContracts.UserContext userContext;
	 		
		[WCF::MessageBodyMember(Name = "RequestIdChangeIdCollection")] 
		public Web09.Services.DataContracts.ResultAdjustmentChangeCollection RequestIdChangeIdCollection
		{
			get { return requestIdChangeIdCollection; }
			set { requestIdChangeIdCollection = value; }
		}
			
		[WCF::MessageBodyMember(Name = "ScrutinyStatusCode")] 
		public string ScrutinyStatusCode
		{
			get { return scrutinyStatusCode; }
			set { scrutinyStatusCode = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Comments")] 
		public string Comments
		{
			get { return comments; }
			set { comments = value; }
		}
			
		[WCF::MessageBodyMember(Name = "ReasonId")] 
		public System.Nullable<int> ReasonId
		{
			get { return reasonId; }
			set { reasonId = value; }
		}
			
		[WCF::MessageBodyMember(Name = "UserContext")] 
		public Web09.Services.DataContracts.UserContext UserContext
		{
			get { return userContext; }
			set { userContext = value; }
		}
	}
}

