//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - SaveUserSurveyRequest
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class SaveUserSurveyRequest
	{
		private Web09.Services.DataContracts.UserSurvey userSurveyInfo;
	 		
		[WCF::MessageBodyMember(Name = "UserSurveyInfo")] 
		public Web09.Services.DataContracts.UserSurvey UserSurveyInfo
		{
			get { return userSurveyInfo; }
			set { userSurveyInfo = value; }
		}
	}
}

