//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - SaveCategoryResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class SaveCategoryResponse
	{
		private Web09.Services.DataContracts.FAQCategories categories;
	 		
		[WCF::MessageBodyMember(Name = "Categories")] 
		public Web09.Services.DataContracts.FAQCategories Categories
		{
			get { return categories; }
			set { categories = value; }
		}
	}
}

