//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - SaveFAQListOrderRequest
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class SaveFAQListOrderRequest
	{
		private Web09.Services.DataContracts.FAQs fAQs;
	 		
		[WCF::MessageBodyMember(Name = "FAQs")] 
		public Web09.Services.DataContracts.FAQs FAQs
		{
			get { return fAQs; }
			set { fAQs = value; }
		}
	}
}

