//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - SetUserPasswordPrintedStatusResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "SetUserPasswordPrintedStatusResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class SetUserPasswordPrintedStatusResponse
	{
		private string username;
	 	private Web09.Services.DataContracts.UserContext userContext;
	 		
		[WCF::MessageBodyMember(Name = "Username")] 
		public string Username
		{
			get { return username; }
			set { username = value; }
		}
			
		[WCF::MessageBodyMember(Name = "UserContext")] 
		public Web09.Services.DataContracts.UserContext UserContext
		{
			get { return userContext; }
			set { userContext = value; }
		}
	}
}

