//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - SubmitEditPupilResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "SubmitEditPupilResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class SubmitEditPupilResponse
	{
		private bool isAdjustmentComplete;
	 	private Web09.Services.DataContracts.PromptList promptList;
	 	private Web09.Services.DataContracts.CompletedPupilAdjustment completedAdjustment;
	 	private Web09.Services.DataContracts.ValidationFailureList warningList;
	 	private bool isPupilSaved;
	 	private bool isAdjustmentRequired;
	 	private System.Collections.Generic.List<string> completedMessages;
	 		
		[WCF::MessageBodyMember(Name = "IsAdjustmentComplete")] 
		public bool IsAdjustmentComplete
		{
			get { return isAdjustmentComplete; }
			set { isAdjustmentComplete = value; }
		}
			
		[WCF::MessageBodyMember(Name = "PromptList")] 
		public Web09.Services.DataContracts.PromptList PromptList
		{
			get { return promptList; }
			set { promptList = value; }
		}
			
		[WCF::MessageBodyMember(Name = "CompletedAdjustment")] 
		public Web09.Services.DataContracts.CompletedPupilAdjustment CompletedAdjustment
		{
			get { return completedAdjustment; }
			set { completedAdjustment = value; }
		}
			
		[WCF::MessageBodyMember(Name = "WarningList")] 
		public Web09.Services.DataContracts.ValidationFailureList WarningList
		{
			get { return warningList; }
			set { warningList = value; }
		}
			
		[WCF::MessageBodyMember(Name = "IsPupilSaved")] 
		public bool IsPupilSaved
		{
			get { return isPupilSaved; }
			set { isPupilSaved = value; }
		}
			
		[WCF::MessageBodyMember(Name = "IsAdjustmentRequired")] 
		public bool IsAdjustmentRequired
		{
			get { return isAdjustmentRequired; }
			set { isAdjustmentRequired = value; }
		}
			
		[WCF::MessageBodyMember(Name = "CompletedMessages")] 
		public System.Collections.Generic.List<string> CompletedMessages
		{
			get { return completedMessages; }
			set { completedMessages = value; }
		}
	}
}

