//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - SubmitAddPupilRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "SubmitAddPupilRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class SubmitAddPupilRequest
	{
		private Web09.Services.DataContracts.PupilDetails pupil;
	 	private Web09.Services.DataContracts.PromptAnswerList pupiAdjustmentlPromptAnswers;
	 	private string evidence;
	 		
		[WCF::MessageBodyMember(Name = "Pupil")] 
		public Web09.Services.DataContracts.PupilDetails Pupil
		{
			get { return pupil; }
			set { pupil = value; }
		}
			
		[WCF::MessageBodyMember(Name = "PupiAdjustmentlPromptAnswers")] 
		public Web09.Services.DataContracts.PromptAnswerList PupiAdjustmentlPromptAnswers
		{
			get { return pupiAdjustmentlPromptAnswers; }
			set { pupiAdjustmentlPromptAnswers = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Evidence")] 
		public string Evidence
		{
			get { return evidence; }
			set { evidence = value; }
		}
	}
}

