//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ValidatePupilResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "ValidatePupilResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class ValidatePupilResponse
	{
		private bool isPupilValid;
	 	private Web09.Services.DataContracts.ValidationFailureList warningList;
	 	private Web09.Services.DataContracts.PupilDetails filledPupil;
	 		
		[WCF::MessageBodyMember(Name = "IsPupilValid")] 
		public bool IsPupilValid
		{
			get { return isPupilValid; }
			set { isPupilValid = value; }
		}
			
		[WCF::MessageBodyMember(Name = "WarningList")] 
		public Web09.Services.DataContracts.ValidationFailureList WarningList
		{
			get { return warningList; }
			set { warningList = value; }
		}
			
		[WCF::MessageBodyMember(Name = "FilledPupil")] 
		public Web09.Services.DataContracts.PupilDetails FilledPupil
		{
			get { return filledPupil; }
			set { filledPupil = value; }
		}
	}
}

