//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ValidatePupilRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "ValidatePupilRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class ValidatePupilRequest
	{
		private Web09.Services.DataContracts.PupilDetails pupil;
	 	private Web09.Services.DataContracts.PupilEditType pupilEditType;
	 	private Web09.Services.DataContracts.ValidationFailureList acknowledgedWarnings;
	 		
		[WCF::MessageBodyMember(Name = "Pupil")] 
		public Web09.Services.DataContracts.PupilDetails Pupil
		{
			get { return pupil; }
			set { pupil = value; }
		}
			
		[WCF::MessageBodyMember(Name = "PupilEditType")] 
		public Web09.Services.DataContracts.PupilEditType PupilEditType
		{
			get { return pupilEditType; }
			set { pupilEditType = value; }
		}
			
		[WCF::MessageBodyMember(Name = "AcknowledgedWarnings")] 
		public Web09.Services.DataContracts.ValidationFailureList AcknowledgedWarnings
		{
			get { return acknowledgedWarnings; }
			set { acknowledgedWarnings = value; }
		}
	}
}

