//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dfe.Rscd.Api {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Dfe.Rscd.Api.Services.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ArrivalDateQuestion_Title {
            get {
                return ResourceManager.GetString("ArrivalDateQuestion.Title", resourceCulture);
            }
        }
        
        internal static string ArrivalDateQuestion_Label {
            get {
                return ResourceManager.GetString("ArrivalDateQuestion.Label", resourceCulture);
            }
        }
        
        internal static string ArrivalDateQuestion_Yes_Description {
            get {
                return ResourceManager.GetString("ArrivalDateQuestion.Yes.Description", resourceCulture);
            }
        }
        
        internal static string ArrivalDateQuestion_No_Description {
            get {
                return ResourceManager.GetString("ArrivalDateQuestion.No.Description", resourceCulture);
            }
        }
        
        internal static string ArrivalDateQuestion_InvalidErrorMessage {
            get {
                return ResourceManager.GetString("ArrivalDateQuestion.InvalidErrorMessage", resourceCulture);
            }
        }
        
        internal static string ArrivalDateQuestion_NullErrorMessage {
            get {
                return ResourceManager.GetString("ArrivalDateQuestion.NullErrorMessage", resourceCulture);
            }
        }
        
        internal static string ArrivalDateQuestion_Date_Title {
            get {
                return ResourceManager.GetString("ArrivalDateQuestion.Date.Title", resourceCulture);
            }
        }
        
        internal static string ArrivalDateQuestion_Date_Label {
            get {
                return ResourceManager.GetString("ArrivalDateQuestion.Date.Label", resourceCulture);
            }
        }
        
        internal static string CountryPupilLeftEnglandFor_Select_Title {
            get {
                return ResourceManager.GetString("CountryPupilLeftEnglandFor.Select.Title", resourceCulture);
            }
        }
        
        internal static string CountryPupilLeftEnglandFor_Select_Label {
            get {
                return ResourceManager.GetString("CountryPupilLeftEnglandFor.Select.Label", resourceCulture);
            }
        }
        
        internal static string CountryPupilLeftEnglandFor_Select_NullErrorMessage {
            get {
                return ResourceManager.GetString("CountryPupilLeftEnglandFor.Select.NullErrorMessage", resourceCulture);
            }
        }
        
        internal static string CountryPupilLeftEnglandFor_Other_Title {
            get {
                return ResourceManager.GetString("CountryPupilLeftEnglandFor.Other.Title", resourceCulture);
            }
        }
        
        internal static string CountryPupilLeftEnglandFor_Other_Label {
            get {
                return ResourceManager.GetString("CountryPupilLeftEnglandFor.Other.Label", resourceCulture);
            }
        }
        
        internal static string CountryPupilLeftEnglandFor_Other_InvalidErrorMessage {
            get {
                return ResourceManager.GetString("CountryPupilLeftEnglandFor.Other.InvalidErrorMessage", resourceCulture);
            }
        }
        
        internal static string CountryPupilLeftEnglandFor_Other_NullErrorMessage {
            get {
                return ResourceManager.GetString("CountryPupilLeftEnglandFor.Other.NullErrorMessage", resourceCulture);
            }
        }
        
        internal static string EvidenceUploadQuestion_Boolean_Title {
            get {
                return ResourceManager.GetString("EvidenceUploadQuestion.Boolean.Title", resourceCulture);
            }
        }
        
        internal static string EvidenceUploadQuestion_Boolean_Label {
            get {
                return ResourceManager.GetString("EvidenceUploadQuestion.Boolean.Label", resourceCulture);
            }
        }
        
        internal static string EvidenceUploadQuestion_Boolean_Yes_Description {
            get {
                return ResourceManager.GetString("EvidenceUploadQuestion.Boolean.Yes.Description", resourceCulture);
            }
        }
        
        internal static string EvidenceUploadQuestion_Boolean_No_Description {
            get {
                return ResourceManager.GetString("EvidenceUploadQuestion.Boolean.No.Description", resourceCulture);
            }
        }
        
        internal static string EvidenceUploadQuestion_Boolean_NullErrorMessage {
            get {
                return ResourceManager.GetString("EvidenceUploadQuestion.Boolean.NullErrorMessage", resourceCulture);
            }
        }
        
        internal static string EvidenceUploadQuestion_Upload_Title {
            get {
                return ResourceManager.GetString("EvidenceUploadQuestion.Upload.Title", resourceCulture);
            }
        }
        
        internal static string ExplainYourRequestQuestion_Title {
            get {
                return ResourceManager.GetString("ExplainYourRequestQuestion.Title", resourceCulture);
            }
        }
        
        internal static string ExplainYourRequestQuestion_InvalidErrorMessage {
            get {
                return ResourceManager.GetString("ExplainYourRequestQuestion.InvalidErrorMessage", resourceCulture);
            }
        }
        
        internal static string ExplainYourRequestQuestion_NullErrorMessage {
            get {
                return ResourceManager.GetString("ExplainYourRequestQuestion.NullErrorMessage", resourceCulture);
            }
        }
        
        internal static string LaestabNumberQuestion_Title {
            get {
                return ResourceManager.GetString("LaestabNumberQuestion.Title", resourceCulture);
            }
        }
        
        internal static string LaestabNumberQuestion_Label {
            get {
                return ResourceManager.GetString("LaestabNumberQuestion.Label", resourceCulture);
            }
        }
        
        internal static string LaestabNumberQuestion_NullErrorMessage {
            get {
                return ResourceManager.GetString("LaestabNumberQuestion.NullErrorMessage", resourceCulture);
            }
        }
        
        internal static string LaestabNumberQuestion_InvalidErrorMessage {
            get {
                return ResourceManager.GetString("LaestabNumberQuestion.InvalidErrorMessage", resourceCulture);
            }
        }
        
        internal static string PupilCountryQuestion_Select_Title {
            get {
                return ResourceManager.GetString("PupilCountryQuestion.Select.Title", resourceCulture);
            }
        }
        
        internal static string PupilCountryQuestion_Select_Label {
            get {
                return ResourceManager.GetString("PupilCountryQuestion.Select.Label", resourceCulture);
            }
        }
        
        internal static string PupilCountryQuestion_Select_NullErrorMessage {
            get {
                return ResourceManager.GetString("PupilCountryQuestion.Select.NullErrorMessage", resourceCulture);
            }
        }
        
        internal static string PupilCountryQuestion_Other_Title {
            get {
                return ResourceManager.GetString("PupilCountryQuestion.Other.Title", resourceCulture);
            }
        }
        
        internal static string PupilCountryQuestion_Other_Label {
            get {
                return ResourceManager.GetString("PupilCountryQuestion.Other.Label", resourceCulture);
            }
        }
        
        internal static string PupilCountryQuestion_Other_InvalidErrorMessage {
            get {
                return ResourceManager.GetString("PupilCountryQuestion.Other.InvalidErrorMessage", resourceCulture);
            }
        }
        
        internal static string PupilCountryQuestion_Other_NullErrorMessage {
            get {
                return ResourceManager.GetString("PupilCountryQuestion.Other.NullErrorMessage", resourceCulture);
            }
        }
        
        internal static string PupilDateOffRollQuestion_Title {
            get {
                return ResourceManager.GetString("PupilDateOffRollQuestion.Title", resourceCulture);
            }
        }
        
        internal static string PupilDateOffRollQuestion_Label {
            get {
                return ResourceManager.GetString("PupilDateOffRollQuestion.Label", resourceCulture);
            }
        }
        
        internal static string PupilDateOffRollQuestion_NullErrorMessage {
            get {
                return ResourceManager.GetString("PupilDateOffRollQuestion.NullErrorMessage", resourceCulture);
            }
        }
        
        internal static string PupilDateOffRollQuestion_InvalidErrorMessage {
            get {
                return ResourceManager.GetString("PupilDateOffRollQuestion.InvalidErrorMessage", resourceCulture);
            }
        }
        
        internal static string PupilExclusionDateQuestion_Title {
            get {
                return ResourceManager.GetString("PupilExclusionDateQuestion.Title", resourceCulture);
            }
        }
        
        internal static string PupilExclusionDateQuestion_Label {
            get {
                return ResourceManager.GetString("PupilExclusionDateQuestion.Label", resourceCulture);
            }
        }
        
        internal static string PupilExclusionDateQuestion_NullErrorMessage {
            get {
                return ResourceManager.GetString("PupilExclusionDateQuestion.NullErrorMessage", resourceCulture);
            }
        }
        
        internal static string PupilExclusionDateQuestion_InvalidErrorMessage {
            get {
                return ResourceManager.GetString("PupilExclusionDateQuestion.InvalidErrorMessage", resourceCulture);
            }
        }
        
        internal static string PupilNativeLanguageQuestion_Select_Title {
            get {
                return ResourceManager.GetString("PupilNativeLanguageQuestion.Select.Title", resourceCulture);
            }
        }
        
        internal static string PupilNativeLanguageQuestion_Select_Label {
            get {
                return ResourceManager.GetString("PupilNativeLanguageQuestion.Select.Label", resourceCulture);
            }
        }
        
        internal static string PupilNativeLanguageQuestion_Select_NullErrorMessage {
            get {
                return ResourceManager.GetString("PupilNativeLanguageQuestion.Select.NullErrorMessage", resourceCulture);
            }
        }
        
        internal static string PupilNativeLanguageQuestion_Other_Title {
            get {
                return ResourceManager.GetString("PupilNativeLanguageQuestion.Other.Title", resourceCulture);
            }
        }
        
        internal static string PupilNativeLanguageQuestion_Other_Label {
            get {
                return ResourceManager.GetString("PupilNativeLanguageQuestion.Other.Label", resourceCulture);
            }
        }
        
        internal static string PupilNativeLanguageQuestion_Other_InvalidErrorMessage {
            get {
                return ResourceManager.GetString("PupilNativeLanguageQuestion.Other.InvalidErrorMessage", resourceCulture);
            }
        }
        
        internal static string PupilNativeLanguageQuestion_Other_NullErrorMessage {
            get {
                return ResourceManager.GetString("PupilNativeLanguageQuestion.Other.NullErrorMessage", resourceCulture);
            }
        }
        
        internal static string RemovePupilOtherMissingInEducation_HTML {
            get {
                return ResourceManager.GetString("RemovePupilOtherMissingInEducation.HTML", resourceCulture);
            }
        }
        
        internal static string RemovePupilOtherInPrisonRemandCentreSecureUnitRule_HTML {
            get {
                return ResourceManager.GetString("RemovePupilOtherInPrisonRemandCentreSecureUnitRule.HTML", resourceCulture);
            }
        }
        
        internal static string RemovePupilOtherElectiveHomeEducationRule_HTML {
            get {
                return ResourceManager.GetString("RemovePupilOtherElectiveHomeEducationRule.HTML", resourceCulture);
            }
        }
        
        internal static string RemovePupilOtherPermanentlyExcluded_HTML {
            get {
                return ResourceManager.GetString("RemovePupilOtherPermanentlyExcluded.HTML", resourceCulture);
            }
        }
        
        internal static string RemovePupilOtherPoliceInvolvementBailRule_HTML {
            get {
                return ResourceManager.GetString("RemovePupilOtherPoliceInvolvementBailRule.HTML", resourceCulture);
            }
        }
        
        internal static string RemovePupilOtherSafeguardingFapRule_HTML {
            get {
                return ResourceManager.GetString("RemovePupilOtherSafeguardingFapRule.HTML", resourceCulture);
            }
        }
        
        internal static string RemovePupilOtherTerminalLongIllnessRule_HTML {
            get {
                return ResourceManager.GetString("RemovePupilOtherTerminalLongIllnessRule.HTML", resourceCulture);
            }
        }
        
        internal static string RemovePupilPermanentlyLeftEngland_HTML {
            get {
                return ResourceManager.GetString("RemovePupilPermanentlyLeftEngland.HTML", resourceCulture);
            }
        }
        
        internal static string RemovePupilOtherEalExceptionalCirumstances_HTML {
            get {
                return ResourceManager.GetString("RemovePupilOtherEalExceptionalCirumstances.HTML", resourceCulture);
            }
        }
    }
}
