//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dfe.Rscd.Api.BusinessLogic.Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dfe.Rscd.Api.BusinessLogic.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid FAQ ID..
        /// </summary>
        internal static string MSG0000 {
            get {
                return ResourceManager.GetString("MSG0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid FAQ Category ID..
        /// </summary>
        internal static string MSG0001 {
            get {
                return ResourceManager.GetString("MSG0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete FAQ Information..
        /// </summary>
        internal static string MSG0002 {
            get {
                return ResourceManager.GetString("MSG0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DCSF Number..
        /// </summary>
        internal static string MSG0003 {
            get {
                return ResourceManager.GetString("MSG0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Keystage..
        /// </summary>
        internal static string MSG0004 {
            get {
                return ResourceManager.GetString("MSG0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred on website..
        /// </summary>
        internal static string MSG0005 {
            get {
                return ResourceManager.GetString("MSG0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid School Group..
        /// </summary>
        internal static string MSG0006 {
            get {
                return ResourceManager.GetString("MSG0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Help ID..
        /// </summary>
        internal static string MSG0007 {
            get {
                return ResourceManager.GetString("MSG0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Page ID..
        /// </summary>
        internal static string MSG0008 {
            get {
                return ResourceManager.GetString("MSG0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Help Information..
        /// </summary>
        internal static string MSG0009 {
            get {
                return ResourceManager.GetString("MSG0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Message ID..
        /// </summary>
        internal static string MSG0010 {
            get {
                return ResourceManager.GetString("MSG0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Message Type ID..
        /// </summary>
        internal static string MSG0011 {
            get {
                return ResourceManager.GetString("MSG0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Message Information..
        /// </summary>
        internal static string MSG0012 {
            get {
                return ResourceManager.GetString("MSG0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Result ID..
        /// </summary>
        internal static string MSG0013 {
            get {
                return ResourceManager.GetString("MSG0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid QAN..
        /// </summary>
        internal static string MSG0014 {
            get {
                return ResourceManager.GetString("MSG0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Syllabus Code..
        /// </summary>
        internal static string MSG0015 {
            get {
                return ResourceManager.GetString("MSG0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Awarding Organisation..
        /// </summary>
        internal static string MSG0016 {
            get {
                return ResourceManager.GetString("MSG0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Exam Year..
        /// </summary>
        internal static string MSG0017 {
            get {
                return ResourceManager.GetString("MSG0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Exam Season..
        /// </summary>
        internal static string MSG0018 {
            get {
                return ResourceManager.GetString("MSG0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Student ID..
        /// </summary>
        internal static string MSG0019 {
            get {
                return ResourceManager.GetString("MSG0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalild Adjustment Reason ID..
        /// </summary>
        internal static string MSG0020 {
            get {
                return ResourceManager.GetString("MSG0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Prompt ID..
        /// </summary>
        internal static string MSG0021 {
            get {
                return ResourceManager.GetString("MSG0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data concurrency error. The requested update is out of date. Please re-start the update process..
        /// </summary>
        internal static string MSG0022 {
            get {
                return ResourceManager.GetString("MSG0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks are not within correct range for the grade..
        /// </summary>
        internal static string MSG0023 {
            get {
                return ResourceManager.GetString("MSG0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested that this result be withdrawn. If you wish to keep or amend the result please cancel the withdrawal request.
        /// </summary>
        internal static string MSG0024 {
            get {
                return ResourceManager.GetString("MSG0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result for the selected exam year, season and subject already exists. Please admend and re-submit separately.
        /// </summary>
        internal static string MSG0025 {
            get {
                return ResourceManager.GetString("MSG0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks are not within correct range for the grade..
        /// </summary>
        internal static string MSG0026 {
            get {
                return ResourceManager.GetString("MSG0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note the grade conflict between a late result and a request..
        /// </summary>
        internal static string MSG0027 {
            get {
                return ResourceManager.GetString("MSG0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This late result matches an unamended or requested result below. Please amend that if not correct.
        /// </summary>
        internal static string MSG0028 {
            get {
                return ResourceManager.GetString("MSG0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that the matching late result above has not been rejected.
        /// </summary>
        internal static string MSG0029 {
            get {
                return ResourceManager.GetString("MSG0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request matched a late result..
        /// </summary>
        internal static string MSG0030 {
            get {
                return ResourceManager.GetString("MSG0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request matched a late result. Instead please ensure that the late result is agreed..
        /// </summary>
        internal static string MSG0031 {
            get {
                return ResourceManager.GetString("MSG0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient student information provided..
        /// </summary>
        internal static string MSG0032 {
            get {
                return ResourceManager.GetString("MSG0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient information provided as answer to student adjustment prompts.
        /// </summary>
        internal static string MSG0033 {
            get {
                return ResourceManager.GetString("MSG0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Student Include/Remove adjustment request.
        /// </summary>
        internal static string MSG0034 {
            get {
                return ResourceManager.GetString("MSG0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Student Edit request.
        /// </summary>
        internal static string MSG0035 {
            get {
                return ResourceManager.GetString("MSG0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error attaching evidence to the result.
        /// </summary>
        internal static string MSG0036 {
            get {
                return ResourceManager.GetString("MSG0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An outstanding adjustment request exists for this pupil. You cannot generate another request..
        /// </summary>
        internal static string MSG0037 {
            get {
                return ResourceManager.GetString("MSG0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pupil adjustment is required for KS5 admission date updates..
        /// </summary>
        internal static string MSG0038 {
            get {
                return ResourceManager.GetString("MSG0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pupil adjustments for Key Stage 3 pupils are not allowed..
        /// </summary>
        internal static string MSG0039 {
            get {
                return ResourceManager.GetString("MSG0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student validation failed for the following reasons:.
        /// </summary>
        internal static string MSG0040 {
            get {
                return ResourceManager.GetString("MSG0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes made to the student require a student adjustment request to be created. The student already has an outstanding request. Additional requests cannot be made unless existing request is cancelled..
        /// </summary>
        internal static string MSG0041 {
            get {
                return ResourceManager.GetString("MSG0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes were detected for the student. The student details were not updated..
        /// </summary>
        internal static string MSG0042 {
            get {
                return ResourceManager.GetString("MSG0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student validation failed..
        /// </summary>
        internal static string MSG0043 {
            get {
                return ResourceManager.GetString("MSG0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student was not saved. Please try again..
        /// </summary>
        internal static string MSG0044 {
            get {
                return ResourceManager.GetString("MSG0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving school NOR update request..
        /// </summary>
        internal static string MSG0045 {
            get {
                return ResourceManager.GetString("MSG0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A school NOR request has already been created for this school.
        /// </summary>
        internal static string MSG0046 {
            get {
                return ResourceManager.GetString("MSG0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already added this result with a different grade. Please cancel the earlier addition first..
        /// </summary>
        internal static string MSG0047 {
            get {
                return ResourceManager.GetString("MSG0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already amended this result to a different grade. Please revise that amendment if you want to change the grade again..
        /// </summary>
        internal static string MSG0048 {
            get {
                return ResourceManager.GetString("MSG0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please amend the listed result instead of adding a new result..
        /// </summary>
        internal static string MSG0049 {
            get {
                return ResourceManager.GetString("MSG0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;re late results published for this qualification. Please review the late results and, if they are incorrect, supply a new grade..
        /// </summary>
        internal static string MSG0050 {
            get {
                return ResourceManager.GetString("MSG0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application error: The request is not found..
        /// </summary>
        internal static string MSG0051 {
            get {
                return ResourceManager.GetString("MSG0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date value provided for adjustment prompt..
        /// </summary>
        internal static string MSG0052 {
            get {
                return ResourceManager.GetString("MSG0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School with DFES Number {0} is not found in the database..
        /// </summary>
        internal static string MSG0053 {
            get {
                return ResourceManager.GetString("MSG0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key stage for adding a pupil..
        /// </summary>
        internal static string MSG0054 {
            get {
                return ResourceManager.GetString("MSG0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No student record found with a StudentID value of {0}.
        /// </summary>
        internal static string MSG0055 {
            get {
                return ResourceManager.GetString("MSG0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already logged..
        /// </summary>
        internal static string MSG0056 {
            get {
                return ResourceManager.GetString("MSG0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matching result is already listed..
        /// </summary>
        internal static string MSG0057 {
            get {
                return ResourceManager.GetString("MSG0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This student will not be included in the KS5 publication if request accepted..
        /// </summary>
        internal static string MSG0058 {
            get {
                return ResourceManager.GetString("MSG0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years above 13 cannot be accepted - student was not reported in previous years Tables and is now at the end of KS5 studies..
        /// </summary>
        internal static string MSG0059 {
            get {
                return ResourceManager.GetString("MSG0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student was deferred last year and cannot be deferred again.
        /// </summary>
        internal static string MSG0060 {
            get {
                return ResourceManager.GetString("MSG0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student cannot be deferred because they will be too old to be published in next years Performance Tables.
        /// </summary>
        internal static string MSG0061 {
            get {
                return ResourceManager.GetString("MSG0061", resourceCulture);
            }
        }
    }
}
