using Dfe.Rscd.Api.Domain.Core.Enums;
using Dfe.Rscd.Api.Infrastructure.DynamicsCRM.AutoGenerated;
using System;

namespace Dfe.Rscd.Api.Infrastructure.DynamicsCRM.Extensions
{
    public static class AmendmentTypeExtension
    {
        public static AmendmentType ToDomainAmendmentType(this new_Amendment_rscd_Amendmenttype amendmentType)
        {
            switch (amendmentType)
            {
                case new_Amendment_rscd_Amendmenttype.Addpupil:
                    return AmendmentType.AddPupil;
                case new_Amendment_rscd_Amendmenttype.Removepupil:
                    return AmendmentType.RemovePupil;
                default:
                    throw new ApplicationException();
            }
        }
        public static new_Amendment_rscd_Amendmenttype  ToCRMAmendmentType(this AmendmentType amendmentType)
        {
            switch (amendmentType)
            {
                case AmendmentType.AddPupil:
                    return new_Amendment_rscd_Amendmenttype.Addpupil;
                case AmendmentType.RemovePupil:
                    return new_Amendment_rscd_Amendmenttype.Removepupil;
                default:
                    throw new ApplicationException();
            }
        }
    }
}
