//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - CancelPupilRequestMsg
	/// </summary>
	[WCF::MessageContract(WrapperName = "CancelPupilRequestMsg", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class CancelPupilRequestMsg
	{
		private int requestID;
	 	private Web09.Services.DataContracts.UserContext userContext;
	 		
		[WCF::MessageBodyMember(Name = "RequestID")] 
		public int RequestID
		{
			get { return requestID; }
			set { requestID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "UserContext")] 
		public Web09.Services.DataContracts.UserContext UserContext
		{
			get { return userContext; }
			set { userContext = value; }
		}
	}
}

