//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - DoesStudentHaveOutstandingAdjustmentResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "DoesStudentHaveOutstandingAdjustmentResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class DoesStudentHaveOutstandingAdjustmentResponse
	{
		private bool hasOutstandingAdjustment;
	 		
		[WCF::MessageBodyMember(Name = "HasOutstandingAdjustment")] 
		public bool HasOutstandingAdjustment
		{
			get { return hasOutstandingAdjustment; }
			set { hasOutstandingAdjustment = value; }
		}
	}
}

