//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetCohortAdjustmentStudentRequestResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetCohortAdjustmentStudentRequestResponse
	{
		private Web09.Services.DataContracts.CohortAdjustmentRequest cohortAdjustmentRequest;
	 		
		[WCF::MessageBodyMember(Name = "CohortAdjustmentRequest")] 
		public Web09.Services.DataContracts.CohortAdjustmentRequest CohortAdjustmentRequest
		{
			get { return cohortAdjustmentRequest; }
			set { cohortAdjustmentRequest = value; }
		}
	}
}

