//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetCohortAdjustmentRequestCountRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetCohortAdjustmentRequestCountRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetCohortAdjustmentRequestCountRequest
	{
		private Web09.Services.DataContracts.CohortAdjustmentRequestsFilter cohortAdjustmentRequestFilter;
	 	private System.Nullable<bool> isJuneDecisionsRequests;
	 		
		[WCF::MessageBodyMember(Name = "CohortAdjustmentRequestFilter")] 
		public Web09.Services.DataContracts.CohortAdjustmentRequestsFilter CohortAdjustmentRequestFilter
		{
			get { return cohortAdjustmentRequestFilter; }
			set { cohortAdjustmentRequestFilter = value; }
		}
			
		[WCF::MessageBodyMember(Name = "IsJuneDecisionsRequests")] 
		public System.Nullable<bool> IsJuneDecisionsRequests
		{
			get { return isJuneDecisionsRequests; }
			set { isJuneDecisionsRequests = value; }
		}
	}
}

