//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetCohortDetailsCountRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetCohortDetailsCountRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class GetCohortDetailsCountRequest
	{
		private Web09.Services.DataContracts.PupilFilterParams filterParams;
	 		
		[WCF::MessageBodyMember(Name = "FilterParams")] 
		public Web09.Services.DataContracts.PupilFilterParams FilterParams
		{
			get { return filterParams; }
			set { filterParams = value; }
		}
	}
}

