//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetCohortDetailsRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetCohortDetailsRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class GetCohortDetailsRequest
	{
		private int rowsPerPage;
	 	private int page;
	 	private Web09.Services.DataContracts.PupilFilterParams filterParams;
	 	private string sortExpression;
	 		
		[WCF::MessageBodyMember(Name = "RowsPerPage")] 
		public int RowsPerPage
		{
			get { return rowsPerPage; }
			set { rowsPerPage = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Page")] 
		public int Page
		{
			get { return page; }
			set { page = value; }
		}
			
		[WCF::MessageBodyMember(Name = "FilterParams")] 
		public Web09.Services.DataContracts.PupilFilterParams FilterParams
		{
			get { return filterParams; }
			set { filterParams = value; }
		}
			
		[WCF::MessageBodyMember(Name = "SortExpression")] 
		public string SortExpression
		{
			get { return sortExpression; }
			set { sortExpression = value; }
		}
	}
}

