//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetDCSFNotificationRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetDCSFNotificationRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetDCSFNotificationRequest
	{
		private int reasonID;
	 	private bool isPLASCField;
	 	private short keystageID;
	 	private string requestType;
	 		
		[WCF::MessageBodyMember(Name = "ReasonID")] 
		public int ReasonID
		{
			get { return reasonID; }
			set { reasonID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "isPLASC")] 
		public bool isPLASC
		{
			get { return isPLASCField; }
			set { isPLASCField = value; }
		}
			
		[WCF::MessageBodyMember(Name = "KeystageID")] 
		public short KeystageID
		{
			get { return keystageID; }
			set { keystageID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "RequestType")] 
		public string RequestType
		{
			get { return requestType; }
			set { requestType = value; }
		}
	}
}

