//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetGradesRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetGradesRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class GetGradesRequest
	{
		private int qualificationID;
	 	private short keyStageID;
	 	private short studentKeyStageID;
	 		
		[WCF::MessageBodyMember(Name = "QualificationID")] 
		public int QualificationID
		{
			get { return qualificationID; }
			set { qualificationID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "KeyStageID")] 
		public short KeyStageID
		{
			get { return keyStageID; }
			set { keyStageID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "StudentKeyStageID")] 
		public short StudentKeyStageID
		{
			get { return studentKeyStageID; }
			set { studentKeyStageID = value; }
		}
	}
}

