//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetLateResultsV2Response
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetLateResultsV2Response", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class GetLateResultsV2Response
	{
		private string lateResultsPageJSON;
	 	private int lateResultsCount;
	 		
		[WCF::MessageBodyMember(Name = "LateResultsPageJSON")] 
		public string LateResultsPageJSON
		{
			get { return lateResultsPageJSON; }
			set { lateResultsPageJSON = value; }
		}
			
		[WCF::MessageBodyMember(Name = "LateResultsCount")] 
		public int LateResultsCount
		{
			get { return lateResultsCount; }
			set { lateResultsCount = value; }
		}
	}
}

