//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetPageListResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetPageListResponse
	{
		private Web09.Services.DataContracts.Pages pages;
	 		
		[WCF::MessageBodyMember(Name = "Pages")] 
		public Web09.Services.DataContracts.Pages Pages
		{
			get { return pages; }
			set { pages = value; }
		}
	}
}

