//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetPupilV2Request
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetPupilV2Request", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetPupilV2Request
	{
		private int pupilID;
	 	private string context;
	 		
		[WCF::MessageBodyMember(Name = "PupilID")] 
		public int PupilID
		{
			get { return pupilID; }
			set { pupilID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Context")] 
		public string Context
		{
			get { return context; }
			set { context = value; }
		}
	}
}

