//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetPupilWithResultsPageResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetPupilWithResultsPageResponse", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetPupilWithResultsPageResponse
	{
		private Web09.Services.DataContracts.Results pupilWithResultsList;
	 	private int totalResultCount;
	 		
		[WCF::MessageBodyMember(Name = "PupilWithResultsList")] 
		public Web09.Services.DataContracts.Results PupilWithResultsList
		{
			get { return pupilWithResultsList; }
			set { pupilWithResultsList = value; }
		}
			
		[WCF::MessageBodyMember(Name = "TotalResultCount")] 
		public int TotalResultCount
		{
			get { return totalResultCount; }
			set { totalResultCount = value; }
		}
	}
}

