//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetQualificationsBySchoolResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetQualificationsBySchoolResponse
	{
		private Web09.Services.DataContracts.QualificationCollection qualifications;
	 		
		[WCF::MessageBodyMember(Name = "Qualifications")] 
		public Web09.Services.DataContracts.QualificationCollection Qualifications
		{
			get { return qualifications; }
			set { qualifications = value; }
		}
	}
}

