//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetResultsForMultipleStudentsRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetResultsForMultipleStudentsRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetResultsForMultipleStudentsRequest
	{
		private System.Collections.Generic.List<int> pupilIDList;
	 	private Web09.Services.DataContracts.ResultTypeEnum resultType;
	 	private string qualification;
	 	private string qAN;
	 	private string awardingBody;
	 	private string syllabus;
	 	private short year;
	 	private string session;
	 	private string subjectTitle;
	 	private short studentKeyStage;
	 		
		[WCF::MessageBodyMember(Name = "PupilIDList")] 
		public System.Collections.Generic.List<int> PupilIDList
		{
			get { return pupilIDList; }
			set { pupilIDList = value; }
		}
			
		[WCF::MessageBodyMember(Name = "ResultType")] 
		public Web09.Services.DataContracts.ResultTypeEnum ResultType
		{
			get { return resultType; }
			set { resultType = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Qualification")] 
		public string Qualification
		{
			get { return qualification; }
			set { qualification = value; }
		}
			
		[WCF::MessageBodyMember(Name = "QAN")] 
		public string QAN
		{
			get { return qAN; }
			set { qAN = value; }
		}
			
		[WCF::MessageBodyMember(Name = "AwardingBody")] 
		public string AwardingBody
		{
			get { return awardingBody; }
			set { awardingBody = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Syllabus")] 
		public string Syllabus
		{
			get { return syllabus; }
			set { syllabus = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Year")] 
		public short Year
		{
			get { return year; }
			set { year = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Session")] 
		public string Session
		{
			get { return session; }
			set { session = value; }
		}
			
		[WCF::MessageBodyMember(Name = "SubjectTitle")] 
		public string SubjectTitle
		{
			get { return subjectTitle; }
			set { subjectTitle = value; }
		}
			
		[WCF::MessageBodyMember(Name = "StudentKeyStage")] 
		public short StudentKeyStage
		{
			get { return studentKeyStage; }
			set { studentKeyStage = value; }
		}
	}
}

