//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetSchoolDocumentsRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetSchoolDocumentsRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class GetSchoolDocumentsRequest
	{
		private System.Nullable<int> dFESNumber;
	 		
		[WCF::MessageBodyMember(Name = "DFESNumber")] 
		public System.Nullable<int> DFESNumber
		{
			get { return dFESNumber; }
			set { dFESNumber = value; }
		}
	}
}

