//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetSchoolKeyStageListResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetSchoolKeyStageListResponse
	{
		private Web09.Services.DataContracts.KeyStageList schoolKeyStageList;
	 		
		[WCF::MessageBodyMember(Name = "SchoolKeyStageList")] 
		public Web09.Services.DataContracts.KeyStageList SchoolKeyStageList
		{
			get { return schoolKeyStageList; }
			set { schoolKeyStageList = value; }
		}
	}
}

