//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetTestsRequest
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetTestsRequest
	{
		private short keyStageID;
	 		
		[WCF::MessageBodyMember(Name = "KeyStageID")] 
		public short KeyStageID
		{
			get { return keyStageID; }
			set { keyStageID = value; }
		}
	}
}

