//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - MessageAssignmentRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "MessageAssignmentRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class MessageAssignmentRequest
	{
		private short messageID;
	 	private System.Collections.Generic.List<int> assignSchools;
	 	private System.Collections.Generic.List<int> unAssignSchools;
	 		
		[WCF::MessageBodyMember(Name = "MessageID")] 
		public short MessageID
		{
			get { return messageID; }
			set { messageID = value; }
		}
			
		[WCF::MessageBodyMember(Name = "AssignSchools")] 
		public System.Collections.Generic.List<int> AssignSchools
		{
			get { return assignSchools; }
			set { assignSchools = value; }
		}
			
		[WCF::MessageBodyMember(Name = "UnAssignSchools")] 
		public System.Collections.Generic.List<int> UnAssignSchools
		{
			get { return unAssignSchools; }
			set { unAssignSchools = value; }
		}
	}
}

