//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - SaveKeystageConfigurationListRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "SaveKeystageConfigurationListRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class SaveKeystageConfigurationListRequest
	{
		private Web09.Services.DataContracts.KeyStageConfigurationList keystageConfigurationList;
	 		
		[WCF::MessageBodyMember(Name = "KeystageConfigurationList")] 
		public Web09.Services.DataContracts.KeyStageConfigurationList KeystageConfigurationList
		{
			get { return keystageConfigurationList; }
			set { keystageConfigurationList = value; }
		}
	}
}

