//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ScanBarcodeV2Request
	/// </summary>
	[WCF::MessageContract(WrapperName = "ScanBarcodeV2Request", WrapperNamespace = "http://www.forvus.co.uk/Web09/services")] 
	public partial class ScanBarcodeV2Request
	{
		private string barCode;
	 	private string username;
	 	private string forename;
	 	private string surname;
	 	private string rolename;
	 		
		[WCF::MessageBodyMember(Name = "BarCode")] 
		public string BarCode
		{
			get { return barCode; }
			set { barCode = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Username")] 
		public string Username
		{
			get { return username; }
			set { username = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Forename")] 
		public string Forename
		{
			get { return forename; }
			set { forename = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Surname")] 
		public string Surname
		{
			get { return surname; }
			set { surname = value; }
		}
			
		[WCF::MessageBodyMember(Name = "Rolename")] 
		public string Rolename
		{
			get { return rolename; }
			set { rolename = value; }
		}
	}
}

