//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - SubmitEditPupilWithCompletedAdjustmentRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "SubmitEditPupilWithCompletedAdjustmentRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class SubmitEditPupilWithCompletedAdjustmentRequest
	{
		private Web09.Services.DataContracts.PupilDetails updatedPupil;
	 	private Web09.Services.DataContracts.CompletedPupilAdjustment completedPupilAdjustment;
	 	private Web09.Services.DataContracts.UserContext userContext;
	 		
		[WCF::MessageBodyMember(Name = "UpdatedPupil")] 
		public Web09.Services.DataContracts.PupilDetails UpdatedPupil
		{
			get { return updatedPupil; }
			set { updatedPupil = value; }
		}
			
		[WCF::MessageBodyMember(Name = "CompletedPupilAdjustment")] 
		public Web09.Services.DataContracts.CompletedPupilAdjustment CompletedPupilAdjustment
		{
			get { return completedPupilAdjustment; }
			set { completedPupilAdjustment = value; }
		}
			
		[WCF::MessageBodyMember(Name = "UserContext")] 
		public Web09.Services.DataContracts.UserContext UserContext
		{
			get { return userContext; }
			set { userContext = value; }
		}
	}
}

