//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Web09.Services.MessageContracts
{
	/// <summary>
	/// Service Contract Class - SubmitEditPupilRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "SubmitEditPupilRequest", WrapperNamespace = "http://www.forvus.co.uk/Web09/scm")] 
	public partial class SubmitEditPupilRequest
	{
		private Web09.Services.DataContracts.PupilDetails pupil;
	 	private Web09.Services.DataContracts.PromptAnswerList pupilAdjustmentPromptAnswers;
	 	private Web09.Services.DataContracts.UserContext userContext;
	 	private Web09.Services.DataContracts.ValidationFailureList acknowledgedWarnings;
	 		
		[WCF::MessageBodyMember(Name = "Pupil")] 
		public Web09.Services.DataContracts.PupilDetails Pupil
		{
			get { return pupil; }
			set { pupil = value; }
		}
			
		[WCF::MessageBodyMember(Name = "PupilAdjustmentPromptAnswers")] 
		public Web09.Services.DataContracts.PromptAnswerList PupilAdjustmentPromptAnswers
		{
			get { return pupilAdjustmentPromptAnswers; }
			set { pupilAdjustmentPromptAnswers = value; }
		}
			
		[WCF::MessageBodyMember(Name = "UserContext")] 
		public Web09.Services.DataContracts.UserContext UserContext
		{
			get { return userContext; }
			set { userContext = value; }
		}
			
		[WCF::MessageBodyMember(Name = "AcknowledgedWarnings")] 
		public Web09.Services.DataContracts.ValidationFailureList AcknowledgedWarnings
		{
			get { return acknowledgedWarnings; }
			set { acknowledgedWarnings = value; }
		}
	}
}

