
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Dfe.Rscd.Api.Infrastructure.DynamicsCRM.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum cr3d5_Decision
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approvedandescalated = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approvedandfinal = 978790000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rejectedandescalated = 353910001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rejectedandfinal = 978790001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum cr3d5_Finaldecision
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approvedandfinal = 353910000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rejectedandfinal = 353910001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum cr3d5_Gender
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Female = 978790001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Male = 978790000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum new_reviewandconfirmschool_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum rscd_Amendment_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum rscd_Amendmenttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Addapupil = 501940000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Addastudent = 501940004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Addoramendaresult = 501940002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Removeapupil = 501940001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Removearesult = 501940003,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum rscd_Checkingwindow
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KS2 = 501940000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KS2Errata = 501940001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KS4Errata = 501940004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KS4June = 501940002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KS4Late = 501940003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KS5 = 501940005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KS5Errata = 501940006,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum rscd_Establishment_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum rscd_Evidencestatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Later = 501940001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Notrequired = 501940002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Now = 501940000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum rscd_Outcome
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approvedandfinal = 501940005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Autoapproved = 501940000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Autorejected = 501940001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AwaitingDfEreview = 501940002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Awaitingevidence = 501940008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AwaitingReviewer2 = 501940003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AwaitingReviewer3 = 501940004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cancelled = 501940007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rejectedandfinal = 501940006,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum rscd_Removepupil_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
}
